import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>subaymuco.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>subaymuco.com</h1>
        <Image src="/muco-images/subay-muco.jpg" alt="subay-muco" width={700} height={500} />
        <p>made by srfzler</p>
      </main>
    </>
  );
}
